### ISSUE TITLE
Using this script will get you BANNED

### ISSUE THREAD

**Issue by n3tman** [Citrinate/gleamSolver#3]
I wasn't using your particular script, but an alternative: https://github.com/Tackyou/Gleam.io-Autosolve

11 of my accounts got banned because of it. One of my friends who was using your script was banned too.

So, people, DON'T USE THESE SCRIPTS! Gleam.io now actively bans people for it. Read here: http://steamcommunity.com/groups/ascfarm/discussions/1/365163686036489825/?tscn=1459603986#c365163686043457571

Or here: https://github.com/Tackyou/Gleam.io-Autosolve/issues/11#issuecomment-204588899

**Comment by Citrinate** [comment]
People have reported to me that they were banned for using this script as well.  It's likely that the bans were due to the scripts running inhumanly fast, and v1.3.1 addresses this issue.

I personally haven't had any accounts banned since starting to use v1.3.1, but I can never guarantee that it won't happen again.

**Comment by undeference** [comment]
I just got "Sorry, you're creating too many entries; try again later" with 1.8.1 (on the last of 17 entries even)

**Comment by Royalgamer06** [comment]
I wonder if you can still win in giveaways you have entered previously, if you are banned. Does somebody know that?

**Comment by Citrinate** [comment]
@undeference Bans probably aren't instant, if they were it would be a whole lot easier to determine exactly what causes them.  If you ever used a previous version of the script on your account, that could still be what caused the ban.

**Comment by undeference** [comment]
It was just a 1 day ban for me and apparently gleam is just broken, since entering manually gets me the same result now.

**Comment by Citrinate** [comment]
While I can never guarantee that the script will never get anyone banned, the issue of bans being guaranteed, at least for now, has been resolved since v1.3.1.  I've also since released an alternative version of the script that doesn't violate the terms of service [here](https://github.com/Citrinate/gleamHelper).

I'll be closing this to avoid any confusion between pre-v1.3.1 bans and any potential future bans.
